package com.idorsia.research.chem.phesa;

import com.actelion.research.chem.Molecule;
import com.actelion.research.chem.MolfileCreator;
import com.actelion.research.chem.MolfileParser;
import com.actelion.research.chem.StereoMolecule;
import com.actelion.research.chem.alignment3d.transformation.TransformationSequence;
import com.actelion.research.chem.conf.Conformer;
import com.actelion.research.chem.conf.SymmetryCorrectedRMSDCalculator;
import com.actelion.research.chem.docking.DockingFailedException;
import com.actelion.research.chem.docking.receptorpharmacophore.NegativeReceptorImageCreator;
import com.actelion.research.chem.docking.shape.ShapeDocking;
import com.actelion.research.chem.io.Mol2FileParser;
import com.actelion.research.chem.phesa.ShapeVolume;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;


/**
 * demonstrates how to use PheSA-based shape docking to dock a ligand into a binding site
 * first step is create a Shape and Pharmacophore representation of the binding site ("Negative Binding Site Image")
 * which then is used in the shape docking algorithm
 */
public class ShapeDockingTest {
	
	
	public static void dock() throws Exception {
		Mol2FileParser m2fp = new Mol2FileParser();
		MolfileParser mfp = new MolfileParser();
		//parse ligand and receptor into StereoMolecules
		StereoMolecule lig = mfp.getCompactMolecule(new File(ShapeDockingTest.class.getClassLoader().getResource("astex_1n46_ligand.mol").toURI()));
		StereoMolecule rec = m2fp.load(new File(ShapeDockingTest.class.getClassLoader().getResource("astex_1n46_protein.mol2").toURI()));
		selfDockShapeOnly(rec,lig);
		
	}
	
	public static void selfDockShapeOnly(StereoMolecule receptor, StereoMolecule nativeLigandPose) throws DockingFailedException  {
		double rmsd = -1.0;

		
		StereoMolecule toDock = new StereoMolecule(nativeLigandPose);
		toDock.ensureHelperArrays(Molecule.cHelperParities);
		//we can store the transformation that is generated by the NegativeReceptorImageCreator to place the 
		//binding site in the origin of the coordinate system, so that we can later backtransform the 
		//aligned ligand and inspect the pose with respect to the original protein structure if desired
		TransformationSequence transform = new TransformationSequence();
		ShapeVolume bsVolume = NegativeReceptorImageCreator.create(nativeLigandPose, receptor,transform);
		ShapeDocking shapeDocking = new ShapeDocking(bsVolume,transform);
		//shape docking creates a list of poses, we take the first one which is the highest-scored
		StereoMolecule docked = shapeDocking.dock(toDock).get(0);
		
		//we use a symmetry corrected rmsd calculator to check how close we are to the true bioactive conformer
		SymmetryCorrectedRMSDCalculator rmsdCalc = new SymmetryCorrectedRMSDCalculator(new Conformer(nativeLigandPose),
					new Conformer(shapeDocking.dock(toDock).get(0)));

		rmsd = rmsdCalc.calculate();

		System.out.println(rmsd);
			
		String delim = System.getProperty("line.separator");
		File outfile = new File(receptor.getName()+ "_docked.sdf");
		   FileWriter fileWriter;
		try {
			
		    fileWriter = new FileWriter(outfile);
		    MolfileCreator mfc = new MolfileCreator(docked);
		    mfc.writeMolfile(fileWriter);
		    fileWriter.write(delim);
		    fileWriter.write("$$$$");
		    fileWriter.write(delim);
		    fileWriter.flush();
			fileWriter.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
		e.printStackTrace();
		}
			

		

	}


}
